In [31]:
import numpy as np

In [3]:
my_arr = np.arange(10**8)
my_list = list(range(10**8))

In [ ]:
# complete methods and attributes on any object after typing a period
# Autocomplete function keywords
my_arr.data

In [14]:
# question mark (?) before or after a variable will display some general information about the object:
my_arr? 

<p>numpy array operations are much faster than python standard data structures, like list</p>

In [4]:
%time for _ in range(10): my_arr2= my_arr*2

CPU times: user 1.51 s, sys: 3.37 s, total: 4.89 s
Wall time: 4.89 s


In [6]:
%time for _ in range(10): my_list2= my_list*2

CPU times: user 15.7 s, sys: 9.57 s, total: 25.3 s
Wall time: 25.1 s


In [7]:
an_apple = 27

In [8]:
an_example = 42

In [13]:
# tab completion, type a part of variable's name and then press tab 
an_apple

27

<img src='images/keyboard_shortcuts.png'></img>

In [21]:
# magic commands

In [22]:
a = np.random.randn(100,100)

In [23]:
%timeit np.dot(a,a)

44.7 µs ± 2.54 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [24]:
%debug?

In [26]:
# ls without question mark as long as there is no variable whose name is the same with ls

In [27]:
%quickref

In [29]:
%magic

In [30]:
%matplotlib inline

In [32]:
data = np.random.randn(2,3)

In [33]:
data

array([[ 0.36671547,  2.35687646,  1.17077498],
       [-0.47881586, -0.89926491,  1.65172647]])

In [34]:
data.dtype # dtype is short for data type

dtype('float64')

In [36]:
data.ndim

2

In [37]:
# np.empty((2, 3, 2)) will return uninitialized “garbage” values

In [38]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [39]:
arr1

array([1., 2., 3.])

In [42]:
numeric_strings = np.array(['1','2'],dtype=np.string_)

In [43]:
numeric_strings.astype(float)

array([1., 2.])

In [44]:
numeric_strings.copy()

<function ndarray.copy>

In [45]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [49]:
cond = names == 'Bob' # assign a condition to cond variable

In [48]:
~cond # ~ used to inverse a general condition

array([False,  True,  True, False,  True,  True,  True])

In [50]:
cond

array([ True, False, False,  True, False, False, False])